version: "3"

includes:
  book:
    taskfile: ./packages/book/
    dir: ./packages/book/

  cargo:
    taskfile: ./packages/mono-dev/task/cargo.yaml
    internal: true

tasks:
  install-cargo-extra-tools:
    aliases: [icets]
    cmds:
      - cargo install txtpp mdbook live-server cargo-expand cargo-watch

  install:
    cmds:
      - magoo install

  test:
    cmds:
      - cargo test

  check:
    desc: Run clippy and other checks
    cmds:
      - task: cargo:clippy-package
        vars:
          PACKAGE: teleparse-macros
      - task: cargo:clippy-package
        vars:
          PACKAGE: teleparse
      - cargo doc
      - task: cargo:fmt-check

  fix:
    cmds:
      - task: cargo:fmt-fix
