version: "3"

includes:
  common:
    taskfile: ./packages/mono-dev/task/common.yaml
    flatten: true
    optional: true

  book:
    taskfile: ./packages/book/
    dir: ./packages/book/
    internal: true

  cargo:
    taskfile: ./packages/mono-dev/task/cargo.yaml
    internal: true

tasks:
  install-cargo-extra-tools:
    aliases: [icets]
    cmds:
      - task: cargo-binstall
        vars:
          PACKAGES: txtpp mdbook live-server cargo-expand cargo-watch

  install:
    cmds:
      - magoo install
      - task: book:install

  test:
    cmds:
      - cargo test --all-features
      - cargo test --no-default-features

  build:
    cmds:
      - cargo build {{.CLI_ARGS}} --all-features
      - cargo build {{.CLI_ARGS}} --no-default-features

  check:
    desc: Run clippy and other checks
    cmds:
      - task: cargo:clippy-package
        vars:
          PACKAGE: teleparse-macros
      - task: cargo:clippy-package
        vars:
          PACKAGE: teleparse
      - cargo doc
      - task: cargo:fmt-check

  fix:
    cmds:
      - task: cargo:fmt-fix

  build-book-ci:
    cmds:
      - task: book:install
      - task: book:build
