version: '3'

includes:
  mdbook:
    taskfile: ../mono-dev/task/mdbook.yaml
    internal: true

tasks:
  install:
    cmds:
      - task: mdbook:install-theme-monorepo
  dev:
    desc: Watch and serve the book
    cmds:
      - txtpp . -r && mdbook build
      - live-server book -p 8081 &
      - cargo watch -s "txtpp packages/book -r -N && mdbook build packages/book"

  build:
    desc: Build the book
    cmds:
      - txtpp . -r
      - mdbook build

