name: Teleparse Book

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  book-build:
    name: Build Book
    runs-on: ubuntu-latest
    steps:
      - uses: Pistonight/mono-dev/actions/setup@main
        with:
          submodules: true
          tool-cargo-binstall: mdbook,mdbook-admonish,txtpp
      - run: task build-book-ci
      - uses: actions/upload-pages-artifact@v3
        with:
          path: packages/book/book
          retention-days: 3

  book-deploy:
    name: Deploy Book
    needs:
      - book-build
    if: github.event_name != 'pull_request'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
