name: Teleparse Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: Pistonight/mono-dev/actions/setup@main
        with:
          submodules: true
          rust: stable
          tool-cargo-install: cargo-expand
      - run: task test
